
PGM_P PSTR_WEBSRV__HTML_INDEX_HTML_DATA();
extern unsigned int WEBSRV__HTML_INDEX_HTML_LENGTH;
PGM_P PSTR_WEBSRV__IMG_THIN_GIF_DATA();
extern unsigned int WEBSRV__IMG_THIN_GIF_LENGTH;
PGM_P PSTR_WEBSRV__IMG_THIN_MINI_GIF_DATA();
extern unsigned int WEBSRV__IMG_THIN_MINI_GIF_LENGTH;
PGM_P PSTR_WEBSRV__IMG_BACKGROUND_GIF_DATA();
extern unsigned int WEBSRV__IMG_BACKGROUND_GIF_LENGTH;
PGM_P PSTR_WEBSRV__JS_REQUIRE_JS_DATA();
extern unsigned int WEBSRV__JS_REQUIRE_JS_LENGTH;
PGM_P PSTR_WEBSRV__JS_SPIN_JS_DATA();
extern unsigned int WEBSRV__JS_SPIN_JS_LENGTH;
PGM_P PSTR_WEBSRV__JS_JQUERY_MIN_JS_DATA();
extern unsigned int WEBSRV__JS_JQUERY_MIN_JS_LENGTH;
